[phases.setup]
nixPkgs = ["nodejs_22", "pnpm-9_x", "openssl", "python3"]

[phases.install]
cmds = ["pnpm install --no-frozen-lockfile"]

[phases.build]
cmds = ["pnpm run build --filter=!@workspace/mockup-sandbox"]

[start]
cmd = "python3 main.py"
